"""
DevelopmentIQ curated team universe — 103 teams (2025-26 season).
79 power-conference + 24 strong mid-major / tournament-relevant programs.
"""

TEAMS_SPEC: list[tuple[str, str, str]] = [
    # Big Ten (18)
    ("illinois", "Illinois", "Big Ten"),
    ("indiana", "Indiana", "Big Ten"),
    ("iowa", "Iowa", "Big Ten"),
    ("maryland", "Maryland", "Big Ten"),
    ("michigan", "Michigan", "Big Ten"),
    ("michigan_state", "Michigan State", "Big Ten"),
    ("minnesota", "Minnesota", "Big Ten"),
    ("nebraska", "Nebraska", "Big Ten"),
    ("northwestern", "Northwestern", "Big Ten"),
    ("ohio_state", "Ohio State", "Big Ten"),
    ("oregon", "Oregon", "Big Ten"),
    ("penn_state", "Penn State", "Big Ten"),
    ("purdue", "Purdue", "Big Ten"),
    ("rutgers", "Rutgers", "Big Ten"),
    ("ucla", "UCLA", "Big Ten"),
    ("usc", "USC", "Big Ten"),
    ("washington", "Washington", "Big Ten"),
    ("wisconsin", "Wisconsin", "Big Ten"),
    # SEC (16)
    ("alabama", "Alabama", "SEC"),
    ("arkansas", "Arkansas", "SEC"),
    ("auburn", "Auburn", "SEC"),
    ("florida", "Florida", "SEC"),
    ("georgia", "Georgia", "SEC"),
    ("kentucky", "Kentucky", "SEC"),
    ("lsu", "LSU", "SEC"),
    ("mississippi_state", "Mississippi State", "SEC"),
    ("missouri", "Missouri", "SEC"),
    ("oklahoma", "Oklahoma", "SEC"),
    ("ole_miss", "Ole Miss", "SEC"),
    ("south_carolina", "South Carolina", "SEC"),
    ("tennessee", "Tennessee", "SEC"),
    ("texas", "Texas", "SEC"),
    ("texas_am", "Texas A&M", "SEC"),
    ("vanderbilt", "Vanderbilt", "SEC"),
    # Big 12 (16)
    ("arizona", "Arizona", "Big 12"),
    ("arizona_state", "Arizona State", "Big 12"),
    ("baylor", "Baylor", "Big 12"),
    ("byu", "BYU", "Big 12"),
    ("cincinnati", "Cincinnati", "Big 12"),
    ("colorado", "Colorado", "Big 12"),
    ("houston", "Houston", "Big 12"),
    ("iowa_state", "Iowa State", "Big 12"),
    ("kansas", "Kansas", "Big 12"),
    ("kansas_state", "Kansas State", "Big 12"),
    ("oklahoma_state", "Oklahoma State", "Big 12"),
    ("tcu", "TCU", "Big 12"),
    ("texas_tech", "Texas Tech", "Big 12"),
    ("ucf", "UCF", "Big 12"),
    ("utah", "Utah", "Big 12"),
    ("west_virginia", "West Virginia", "Big 12"),
    # ACC (18)
    ("boston_college", "Boston College", "ACC"),
    ("california", "California", "ACC"),
    ("clemson", "Clemson", "ACC"),
    ("duke", "Duke", "ACC"),
    ("florida_state", "Florida State", "ACC"),
    ("georgia_tech", "Georgia Tech", "ACC"),
    ("louisville", "Louisville", "ACC"),
    ("miami", "Miami", "ACC"),
    ("nc_state", "NC State", "ACC"),
    ("north_carolina", "North Carolina", "ACC"),
    ("notre_dame", "Notre Dame", "ACC"),
    ("pittsburgh", "Pitt", "ACC"),
    ("smu", "SMU", "ACC"),
    ("stanford", "Stanford", "ACC"),
    ("syracuse", "Syracuse", "ACC"),
    ("virginia", "Virginia", "ACC"),
    ("virginia_tech", "Virginia Tech", "ACC"),
    ("wake_forest", "Wake Forest", "ACC"),
    # Big East (11)
    ("butler", "Butler", "Big East"),
    ("uconn", "UConn", "Big East"),
    ("creighton", "Creighton", "Big East"),
    ("depaul", "DePaul", "Big East"),
    ("georgetown", "Georgetown", "Big East"),
    ("marquette", "Marquette", "Big East"),
    ("providence", "Providence", "Big East"),
    ("seton_hall", "Seton Hall", "Big East"),
    ("st_johns", "St. John's", "Big East"),
    ("villanova", "Villanova", "Big East"),
    ("xavier", "Xavier", "Big East"),
    # Strong mid-majors (23)
    ("gonzaga", "Gonzaga", "WCC"),
    ("saint_marys", "Saint Mary's", "WCC"),
    ("san_francisco", "San Francisco", "WCC"),
    ("santa_clara", "Santa Clara", "WCC"),
    ("san_diego_state", "San Diego State", "MWC"),
    ("san_jose_state", "San Jose State", "MWC"),
    ("new_mexico", "New Mexico", "MWC"),
    ("boise_state", "Boise State", "MWC"),
    ("nevada", "Nevada", "MWC"),
    ("utah_state", "Utah State", "MWC"),
    ("colorado_state", "Colorado State", "MWC"),
    ("unlv", "UNLV", "MWC"),
    ("vcu", "VCU", "A-10"),
    ("dayton", "Dayton", "A-10"),
    ("saint_louis", "Saint Louis", "A-10"),
    ("loyola_chicago", "Loyola Chicago", "A-10"),
    ("memphis", "Memphis", "AAC"),
    ("florida_atlantic", "Florida Atlantic", "AAC"),
    ("north_texas", "North Texas", "AAC"),
    ("uab", "UAB", "AAC"),
    ("drake", "Drake", "MVC"),
    ("bradley", "Bradley", "MVC"),
    ("indiana_state", "Indiana State", "MVC"),
    ("grand_canyon", "Grand Canyon", "WAC"),
]

assert len(TEAMS_SPEC) == 103, f"Expected 103 teams, got {len(TEAMS_SPEC)}"
